import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/design-system/navbar/navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const navbarItems = [{name: "Accueil", href: "/", matcher:'exact'}, {name: "Catalog", href: "/catalog"}, {name: "Location", href: "/location"}, {name: "Map", href: "/map"}];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar menu={navbarItems} />
        <main className="flex-1 p-4">{children}</main>
      </body>
    </html>
  );
}
